import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, RedirectToSignIn } from "@clerk/nextjs"; // RedirectToSignIn'ı ekleyebilirsin
import 'bootstrap/dist/css/bootstrap.min.css';
import ButtonAppBar from "./components/navbar/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Netflix Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} // Publishable Key'i buraya ekle
      // Eğer gerekli ise secretKey de eklenebilir
    >
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ButtonAppBar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
